### PR TITLE
Dashing migration.

### PR DESCRIPTION
**Pull request by BorjaOuterelo**

### CODE REVIEW

**Review by iluetkeb — DISMISSED** [review]
Changes are fine.

Do we still need rclc?

**Comment by tkolcon** [comment]
Looks nice.

**Review by julionce — DISMISSED** [review]

**Comment by BorjaOuterelo** [comment]
@iluetkeb we have still some demos using it. Once ported everything is ported to Dashing, next step will be migrate demos and examples to directly use rcl.

**Comment by iluetkeb** [comment]
Please also open a PR on micro-ros-build, to build using dashing (I can also do it next week, if you'd like).

**Comment by BorjaOuterelo** [comment]
It is on the way.

**Pull request merged**
