### PR TITLE
Update CI with all supported ROS 2 versions

### PR DESCRIPTION
**Pull request by pablogs9**

### CODE REVIEW

**Comment by pablogs9** [comment]
I'm wondering if we should make a `colcon build --cmake-args -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS="-Werror"` to make warning crash the CI.

Thoughs @JanStaschulat?

**Comment by JanStaschulat** [comment]
Yes, good idea.

**Review by JanStaschulat — DISMISSED** [review]

**Review by JanStaschulat — DISMISSED** [review]

**Comment by JanStaschulat** [comment]
currently rolling is: ros:foxy could you also do ros:master? 
I am not sure, but I guess rolling is meant the current master branch?
Any idea how to fix this compiler warning (dashing,eloquent), if it originates from the ROS installation itself?

comment from @ralph-lange: at ros2/rclc PR:https://github.com/ros2/rclc/pull/22#issuecomment-731155783

@JanStaschulat, instead of ros:master, please include Rolling in your tests. It is installed like the other releases by sudo apt install ros-rolling-desktop.

**Comment by pablogs9** [comment]
They don't have `master` docker: https://hub.docker.com/_/ros?tab=tags&page=1

Regarding the errors, they exist also in the build farm. Should we relax these two old distros to `Wpedantic` instead of `Werror`?

**Review by JanStaschulat — DISMISSED** [review]

**Review by JanStaschulat — APPROVED** [review]

**Comment by JanStaschulat** [comment]
@pablogs9 @ralph-lange @norro
Just a comment. 

I think it is a good idea to keep -Wpedantic compiler flag for older versions. Up to now, when creating a PR on micro-ROS/rclc older versions were not checked. Thanks Pablo for setting up the CI jobs for Dashing,Eloquent, Foxy and Rolling release. Now if there is a problem with an older version it should be the job of the maintainer of the package to look into issues about compiler warnings and e..g switch off an compiler option if necessary for a particular ROS version if the problem cannot be solved locally in the package itself (as in the case of the rclc_lifecycle package). 

Goal should be that there are NO compiler warnings and all unit tests pass.

This simplifies the release to ros2/rclc a lot.

**Comment by ralph-lange** [comment]
Yes, we should keep `-Wpedantic`. We should even bring rclc to Quality Level 1 of [REP-2004](https://ros.org/reps/rep-2004.html) in the next months.

I could not find an explicit requested compiler configuration in the REP, but in existing Level 1 packages almost all warnings are enabled, see for example https://github.com/ros2/rclcpp/blob/master/rclcpp/CMakeLists.txt#L32.

**Comment by pablogs9** [comment]
If I have understood, we need to enable these flags in the CMakeLists of the package, not in the CI script right?

**Pull request merged**
