### PR TITLE
Add unitary test for 'rclc_node_init_with_options'

### PR DESCRIPTION
**Pull request by jamoralp**
Related to https://github.com/micro-ROS/rclc/pull/45

### CODE REVIEW

**Comment by pablogs9** [comment]
I'm going to add a Github CI to this

**Comment by pablogs9** [comment]
Hello @JanStaschulat if you are ok with this we are squash-merging.

**Review by pablogs9 — DISMISSED** [review]

**Review by JanStaschulat — CHANGES_REQUESTED** [review]
I updated the source code to test for invalid arguments and updated the unit tests. 
Thanks for configuring the CI job. For some reason it fails. Please resolve this first before merging the PR. Otherwise I am fine with this PR.  

regarding your question https://github.com/micro-ROS/rclc/pull/46#issuecomment-724588738: I am fine with squash-merging

**Review by pablogs9 — APPROVED** [review]

**Comment by pablogs9** [comment]
@JanStaschulat please approve in order to enable the merging option. Checks are passing.

**Review by JanStaschulat — APPROVED** [review]

**Pull request merged**
